// Canonical visual anchors for the bundled Rider–Waite–Smith artwork.
// x/y are normalized against the FULL upright JPG, including its printed border.
// For a reversed image the presentation must transform both axes: 1 - x, 1 - y.
// Evidence describes what is visible; personalized meaning is generated separately.
// Keep this catalogue identical to the server's lib/tarotSymbols.js.
export const cardSymbols = {
  ar00: {id:'cliff_edge',label:'발아래 절벽',x:0.35,y:0.78,evidence:'작은 보따리를 멘 사람이 절벽 가까이 서 있어요.'},
  ar01: {id:'table_tools',label:'탁자 위 네 가지 도구',x:0.36,y:0.59,evidence:'탁자에는 컵, 검, 동전, 지팡이가 놓여 있어요.'},
  ar02: {id:'partly_hidden_scroll',label:'일부 가려진 두루마리',x:0.45,y:0.57,evidence:'손에 든 두루마리는 전부 드러나 있지 않아요.'},
  ar03: {id:'ripe_wheat',label:'앞쪽의 익은 곡식',x:0.59,y:0.84,evidence:'여황제 앞쪽에는 익은 곡식이 펼쳐져 있어요.'},
  ar04: {id:'armor_under_robe',label:'옷 아래 드러난 갑옷',x:0.46,y:0.77,evidence:'황제의 옷 아래로는 갑옷이 보여요.'},
  ar05: {id:'crossed_keys',label:'발치의 교차한 열쇠',x:0.51,y:0.84,evidence:'교황의 발치에는 교차한 열쇠가 있어요.'},
  ar06: {id:'angel_above_pair',label:'두 사람 위의 천사',x:0.51,y:0.31,evidence:'두 사람이 서 있고 그 위로 날개를 편 천사가 보여요.'},
  ar07: {id:'paired_sphinxes',label:'흑백의 두 스핑크스',x:0.72,y:0.77,evidence:'전차 앞에는 검은 스핑크스와 흰 스핑크스가 있어요.'},
  ar08: {id:'hands_at_lion_mouth',label:'사자의 입에 댄 손',x:0.34,y:0.55,evidence:'흰옷을 입은 사람이 사자의 입 근처에 손을 대고 있어요.'},
  ar09: {id:'star_lantern',label:'별빛이 든 등불',x:0.15,y:0.23,evidence:'등불 안에는 별 모양의 빛이 보여요.'},
  ar10: {id:'turning_wheel',label:'가운데 커다란 바퀴',x:0.50,y:0.51,evidence:'커다란 바퀴 주위로 여러 존재가 배치되어 있어요.'},
  ar11: {id:'justice_scales',label:'손에 든 저울',x:0.85,y:0.55,evidence:'왕관을 쓴 인물이 한 손에는 저울, 다른 손에는 곧게 세운 검을 들고 있어요.'},
  ar12: {id:'halo_around_head',label:'거꾸로 매달린 머리의 빛',x:0.48,y:0.78,evidence:'거꾸로 매달린 사람의 머리 주변에는 빛이 보여요.'},
  ar13: {id:'sun_between_towers',label:'두 탑 사이의 태양',x:0.89,y:0.40,evidence:'멀리 두 탑 사이에는 태양이 보여요.'},
  ar14: {id:'water_between_cups',label:'두 잔 사이를 흐르는 물',x:0.48,y:0.40,evidence:'날개 달린 인물이 두 잔 사이로 물을 옮기고 있어요.'},
  ar15: {id:'neck_chain',label:'목에 걸린 사슬',x:0.265,y:0.55,evidence:'두 사람의 목에 걸린 사슬이 받침대에 이어져 있어요.'},
  ar16: {id:'falling_crown',label:'탑에서 떨어지는 왕관',x:0.31,y:0.13,evidence:'탑에 번개가 내리치고 꼭대기의 왕관이 떨어져 나가요.'},
  ar17: {id:'water_returning_to_pool',label:'연못으로 붓는 물',x:0.26,y:0.69,evidence:'기울인 물병의 물은 연못과 땅으로 나뉘어 흘러요.'},
  ar18: {id:'path_between_towers',label:'두 탑 사이로 이어진 길',x:0.51,y:0.51,evidence:'달 아래 두 탑 사이로 길이 멀리 이어져 있어요.'},
  ar19: {id:'bright_sun',label:'밝게 빛나는 태양',x:0.48,y:0.22,evidence:'밝은 태양 아래 아이가 흰 말 위에 앉아 있어요.'},
  ar20: {id:'angel_trumpet',label:'천사가 부는 나팔',x:0.58,y:0.50,evidence:'구름 속 천사가 나팔을 불고 아래의 사람들이 팔을 들어 반응해요.'},
  ar21: {id:'oval_wreath',label:'인물을 둘러싼 화환',x:0.12,y:0.50,evidence:'타원형 화환 안에 한 인물이 두 손의 막대를 들고 있어요.'},
  waac: {id:'sprouting_wand',label:'지팡이에서 돋은 새싹',x:0.35,y:0.11,evidence:'구름에서 나온 손이 싹이 돋은 지팡이를 잡고 있어요.'},
  wa02: {id:'handheld_globe',label:'손에 든 작은 지구본',x:0.36,y:0.37,evidence:'한 사람이 높은 담장 안에서 작은 지구본을 들고 먼 풍경을 바라봐요.'},
  wa03: {id:'ships_on_water',label:'멀리 물 위의 배',x:0.12,y:0.835,evidence:'등을 보인 사람이 높은 곳에서 물 위의 배들을 바라보고 있어요.'},
  wa04: {id:'flower_garland',label:'네 지팡이에 걸린 꽃 장식',x:0.50,y:0.30,evidence:'지팡이 네 개 위로 꽃과 열매 장식이 걸려 있어요.'},
  wa05: {id:'crossing_wands',label:'서로 엇갈린 지팡이',x:0.52,y:0.43,evidence:'지팡이들이 서로 엇갈리고 사람들의 자세도 제각각이에요.'},
  wa06: {id:'laurel_on_wand',label:'지팡이에 걸린 화환',x:0.59,y:0.19,evidence:'말을 탄 사람이 손에 든 지팡이에도 화환이 걸려 있어요.'},
  wa07: {id:'rising_challenger_wands',label:'아래에서 올라오는 지팡이',x:0.39,y:0.80,evidence:'높은 곳의 한 사람이 아래쪽에서 올라오는 여섯 지팡이에 맞서 있어요.'},
  wa08: {id:'flying_wands',label:'한 방향으로 날아가는 지팡이',x:0.64,y:0.38,evidence:'여덟 지팡이가 같은 방향으로 공중을 가로질러요.'},
  wa09: {id:'head_bandage',label:'머리에 감은 붕대',x:0.65,y:0.29,evidence:'머리에 붕대를 감은 사람이 지팡이를 잡고 옆을 살펴요.'},
  wa10: {id:'bundle_of_ten_wands',label:'한꺼번에 안은 열 지팡이',x:0.54,y:0.36,evidence:'한 사람이 열 지팡이를 한꺼번에 안고 몸을 숙인 채 걸어가요.'},
  wapa: {id:'gazing_at_wand',label:'바라보고 있는 지팡이 끝',x:0.70,y:0.15,evidence:'한 젊은 인물이 지팡이를 세워 들고 끝을 바라보고 있어요.'},
  wakn: {id:'rearing_horse',label:'앞발을 든 말',x:0.17,y:0.60,evidence:'기사가 앞발을 든 말을 타고 지팡이를 잡고 있어요.'},
  waqu: {id:'held_sunflower',label:'손에 든 해바라기',x:0.71,y:0.31,evidence:'여왕이 한 손에는 지팡이, 다른 손에는 해바라기를 들고 앉아 있어요.'},
  waki: {id:'sprouting_royal_wand',label:'왕이 든 싹 난 지팡이',x:0.17,y:0.21,evidence:'왕이 싹이 난 지팡이를 들고 왕좌에 앉아 있어요.'},
  peac: {id:'coin_on_palm',label:'손 위에 놓인 동전',x:0.62,y:0.31,evidence:'구름에서 나온 손 위에 별무늬 동전이 놓여 있어요.'},
  pe02: {id:'infinity_ribbon',label:'두 동전을 잇는 무한대 띠',x:0.53,y:0.44,evidence:'두 동전 주위에는 누운 숫자 8 모양의 띠가 이어져 있어요.'},
  pe03: {id:'shared_plan',label:'함께 살펴보는 도면',x:0.505,y:0.64,evidence:'작업하는 사람 곁의 한 사람은 도면처럼 보이는 것을 들고 있어요.'},
  pe04: {id:'coin_held_to_chest',label:'가슴에 꼭 안은 동전',x:0.47,y:0.54,evidence:'한 사람이 동전 하나를 가슴 앞에 꼭 안고 있어요.'},
  pe05: {id:'lit_window',label:'곁에 빛나는 창문',x:0.51,y:0.23,evidence:'창 안에는 동전 다섯 개가 빛나지만 두 사람은 밝은 창문 바깥에 있어요.'},
  pe06: {id:'scales_of_giving',label:'나누는 사람이 든 저울',x:0.85,y:0.47,evidence:'한 사람이 저울을 들고 다른 손으로 동전을 나누어줘요.'},
  pe07: {id:'coin_bearing_plant',label:'동전이 달린 식물',x:0.29,y:0.60,evidence:'한 사람이 도구에 기대어 동전이 달린 식물을 바라보고 있어요.'},
  pe08: {id:'coin_being_worked',label:'손으로 다듬는 동전',x:0.65,y:0.75,evidence:'한 사람이 의자에 앉아 도구로 동전을 다듬고 있어요.'},
  pe09: {id:'bird_on_glove',label:'장갑 낀 손 위의 새',x:0.68,y:0.21,evidence:'장갑 낀 손에는 새가 앉아 있어요.'},
  pe10: {id:'family_under_arch',label:'아치 아래 여러 세대',x:0.62,y:0.51,evidence:'나이 든 인물과 개들, 어른과 아이가 건물의 아치 안팎에 함께 보여요.'},
  pepa: {id:'coin_raised_in_hands',label:'두 손으로 들어 올린 동전',x:0.66,y:0.17,evidence:'한 젊은 인물이 두 손으로 동전을 들어 바라보고 있어요.'},
  pekn: {id:'still_horse',label:'멈춰 서 있는 말',x:0.74,y:0.44,evidence:'갑옷을 입은 기사가 멈춰 선 말 위에서 동전을 들고 있어요.'},
  pequ: {id:'coin_cradled_in_lap',label:'두 손으로 감싼 동전',x:0.32,y:0.44,evidence:'여왕이 무릎 위의 동전을 두 손으로 감싸 바라보고 있어요.'},
  peki: {id:'bull_on_throne',label:'왕좌의 황소 머리',x:0.25,y:0.22,evidence:'왕좌에는 황소 머리 장식이 보여요.'},
  cuac: {id:'flowing_water',label:'컵에서 흐르는 물줄기',x:0.43,y:0.68,evidence:'컵에서는 물줄기가 흘러 아래의 연못으로 이어져요.'},
  cu02: {id:'exchanged_cups',label:'서로 마주 든 두 잔',x:0.60,y:0.40,evidence:'두 사람이 서로 마주 보며 컵을 하나씩 들고 있어요.'},
  cu03: {id:'raised_cups',label:'함께 들어 올린 잔',x:0.50,y:0.20,evidence:'세 사람이 컵을 높이 들고 서로를 향해 모여 있어요.'},
  cu04: {id:'offered_cup',label:'구름에서 건네는 컵',x:0.39,y:0.49,evidence:'구름에서 나온 손이 새로운 컵 하나를 건네요.'},
  cu05: {id:'remaining_cups',label:'등 뒤에 남아 있는 두 잔',x:0.81,y:0.80,evidence:'등 뒤에는 아직 서 있는 컵 두 개가 있어요.'},
  cu06: {id:'flower_cup',label:'꽃을 담아 건네는 잔',x:0.60,y:0.53,evidence:'꽃이 담긴 컵을 한 인물이 다른 작은 인물에게 건네고 있어요.'},
  cu07: {id:'cloud_cups',label:'구름 위의 일곱 잔',x:0.51,y:0.43,evidence:'한 사람이 구름 위에 떠 있는 일곱 컵을 바라보고 있어요.'},
  cu08: {id:'departing_figure',label:'컵을 두고 떠나는 사람',x:0.63,y:0.59,evidence:'한 사람은 컵들을 뒤로한 채 지팡이를 짚고 걸어가요.'},
  cu09: {id:'displayed_cups',label:'가지런히 놓인 아홉 잔',x:0.49,y:0.25,evidence:'뒤의 곡선형 받침 위에는 아홉 컵이 가지런히 놓여 있어요.'},
  cu10: {id:'rainbow_cups',label:'무지개 안의 열 잔',x:0.50,y:0.19,evidence:'하늘의 무지개 안에 열 컵이 놓여 있어요.'},
  cupa: {id:'cup_fish',label:'컵에서 고개를 내민 물고기',x:0.27,y:0.28,evidence:'컵에서는 뜻밖에도 물고기가 고개를 내밀어요.'},
  cukn: {id:'extended_cup',label:'앞으로 내미는 잔',x:0.62,y:0.27,evidence:'갑옷을 입은 기사가 흰 말을 타고 컵을 앞으로 들고 있어요.'},
  cuqu: {id:'covered_cup',label:'뚜껑이 닫힌 잔',x:0.33,y:0.39,evidence:'여왕이 바라보는 특별한 모양의 잔에는 뚜껑이 있어요.'},
  cuki: {id:'surrounding_waves',label:'왕좌를 둘러싼 파도',x:0.14,y:0.72,evidence:'왕이 물 위의 왕좌에 앉아 있고 주변에는 파도가 있어요.'},
  swac: {id:'sword_crown',label:'검 끝의 왕관',x:0.50,y:0.10,evidence:'검 끝에는 왕관과 식물 장식이 걸려 있어요.'},
  sw02: {id:'blindfold',label:'눈을 가린 천',x:0.50,y:0.38,evidence:'눈을 가린 사람이 두 검을 가슴 앞에 교차해 들고 있어요.'},
  sw03: {id:'pierced_heart',label:'세 검이 꽂힌 심장',x:0.51,y:0.48,evidence:'붉은 심장에 세 검이 꽂혀 있어요.'},
  sw04: {id:'folded_hands',label:'가슴 위로 모은 두 손',x:0.59,y:0.58,evidence:'한 인물이 손을 모은 채 누워 있어요.'},
  sw05: {id:'departing_people',label:'등을 돌리고 떠나는 사람들',x:0.20,y:0.72,evidence:'멀어지는 사람들은 등을 보이고 있어요.'},
  sw06: {id:'boat_swords',label:'배에 함께 실린 여섯 검',x:0.65,y:0.44,evidence:'배 앞쪽에는 여섯 검이 꽂혀 있어요.'},
  sw07: {id:'left_swords',label:'뒤에 남겨진 두 검',x:0.80,y:0.62,evidence:'뒤에는 검 두 자루가 남아 있어요.'},
  sw08: {id:'body_bindings',label:'몸을 감싼 끈',x:0.39,y:0.50,evidence:'눈을 가리고 몸이 묶인 사람이 검들 사이에 서 있어요.'},
  sw09: {id:'covered_face',label:'두 손으로 가린 얼굴',x:0.65,y:0.46,evidence:'한 사람이 침대에서 몸을 일으켜 두 손으로 얼굴을 가리고 있어요.'},
  sw10: {id:'bright_horizon',label:'먼 수평선의 밝은 빛',x:0.37,y:0.55,evidence:'위의 하늘은 어둡지만 먼 수평선에는 밝은 빛이 보여요.'},
  swpa: {id:'windblown_hair',label:'바람에 흩날리는 머리카락',x:0.57,y:0.16,evidence:'머리카락과 구름, 뒤의 나무에서 바람의 움직임이 느껴져요.'},
  swkn: {id:'raised_sword',label:'달리며 높이 든 검',x:0.235,y:0.15,evidence:'기사가 검을 높이 들고 달리는 말 위에 몸을 기울이고 있어요.'},
  swqu: {id:'open_hand',label:'앞으로 펼친 손',x:0.70,y:0.37,evidence:'여왕이 한 손에는 검을 곧게 세우고 다른 손은 앞으로 펼치고 있어요.'},
  swki: {id:'held_sword',label:'왕이 손에 든 검',x:0.28,y:0.33,evidence:'왕이 정면을 향해 앉아 한 손에 검을 들고 있어요.'},
};

// A second verified feature on every bundled RWS image. A few visually dense
// cards offer a third or fourth feature; the reader can select 2–4 of them.
const additionalSymbols = {
 ar00:[['white_dog','곁에서 뛰는 흰 개',.79,.76,'흰 개가 절벽을 향해 가는 사람 곁에서 뛰어요.']],
 ar01:[['raised_wand','위로 든 지팡이',.26,.20,'한 손은 지팡이를 위로 들고 다른 손은 아래를 가리켜요.']],
 ar02:[['two_pillars','양쪽의 두 기둥',.18,.44,'여사제는 글자가 새겨진 검고 흰 기둥 사이에 앉아 있어요.']],
 ar03:[['waterfall','옆으로 흐르는 물',.94,.54,'여황제의 오른편으로 물이 흘러내려요.']],
 ar04:[['stone_throne','돌로 된 왕좌',.83,.51,'황제는 숫양 머리가 새겨진 돌 왕좌에 앉아 있어요.']],
 ar05:[['two_followers','앞에 무릎 꿇은 두 사람',.50,.76,'교황 앞에 두 사람이 무릎을 꿇고 있어요.']],
 ar06:[['two_trees','서로 다른 두 나무',.89,.52,'두 사람의 뒤편에는 모습이 다른 나무가 각각 서 있어요.']],
 ar07:[['armored_driver','전차에 선 인물',.52,.43,'갑옷을 입은 사람이 전차 안에 곧게 서 있어요.']],
 ar08:[['infinity_above_head','머리 위 무한대 표식',.30,.18,'사자를 돌보는 사람의 머리 위에 누운 숫자 8이 떠 있어요.']],
 ar09:[['long_staff','다른 손의 긴 지팡이',.46,.57,'등불을 든 사람은 다른 손으로 긴 지팡이를 짚어요.']],
 ar10:[['winged_creatures','구름 속 날개 달린 존재들',.17,.77,'바퀴 둘레의 구름 속에 날개 달린 존재들이 있어요.']],
 ar11:[['upright_sword','곧게 세운 검',.15,.37,'저울과 반대편 손에는 검이 똑바로 서 있어요.']],
 ar12:[['crossed_leg','굽혀 올린 다리',.54,.45,'매달린 사람은 한쪽 다리를 굽혀 다른 다리 뒤로 걸었어요.']],
 ar13:[['white_horse','앞으로 걷는 흰 말',.66,.54,'갑옷을 입은 해골이 흰 말을 타고 앞으로 가요.']],
 ar14:[['feet_in_water','물과 땅에 둔 발',.62,.78,'천사는 한 발을 물에, 다른 발을 땅에 두고 있어요.']],
 ar15:[['loose_chain','느슨하게 걸린 사슬',.65,.66,'사슬의 고리는 목에 바짝 조여 있지 않아요.'],['raised_torch','아래를 향한 횃불',.81,.53,'악마의 손에 든 횃불이 아래쪽을 향해 있어요.']],
 ar16:[['falling_people','탑에서 떨어지는 사람들',.78,.62,'탑의 양옆으로 사람들이 떨어지고 있어요.']],
 ar17:[['large_star','하늘의 큰 별',.51,.18,'하늘 한가운데 큰 별이 빛나고 주위에 작은 별들이 있어요.']],
 ar18:[['crayfish','물에서 나온 가재',.52,.83,'길이 시작되는 물가에는 가재가 올라와 있어요.']],
 ar19:[['child_on_horse','흰 말을 탄 아이',.40,.70,'아이가 흰 말 위에 앉아 붉은 깃발을 들고 있어요.']],
 ar20:[['rising_people','일어서는 사람들',.49,.77,'나팔 아래에서 사람들이 두 팔을 들고 일어나요.']],
 ar21:[['four_corner_figures','네 귀퉁이의 존재들',.87,.18,'화환 바깥 네 귀퉁이에는 서로 다른 존재들이 있어요.']],
 waac:[['hand_from_cloud','구름에서 나온 손',.47,.55,'구름에서 나온 손이 새싹 난 지팡이를 쥐고 있어요.']],
 wa02:[['distant_horizon','담 너머의 먼 풍경',.70,.59,'인물은 담 너머로 바다와 먼 땅을 바라봐요.']],
 wa03:[['three_wands','높이 선 세 지팡이',.80,.51,'인물의 곁과 손에는 세 지팡이가 서 있어요.']],
 wa04:[['people_under_arch','장식 너머의 사람들',.55,.70,'꽃 장식 아래로 사람들이 손을 들어 보여요.']],
 wa05:[['five_people','제각각 움직이는 사람들',.63,.59,'다섯 사람이 서로 다른 방향으로 지팡이를 들고 있어요.']],
 wa06:[['rider_in_crowd','행렬 속 말을 탄 사람',.38,.57,'화환을 쓴 사람이 말 위에서 사람들 사이를 지나가요.']],
 wa07:[['uneven_shoes','서로 다른 신발',.60,.83,'높은 곳에서 맞서는 인물은 발에 서로 다른 신발을 신었어요.']],
 wa08:[['open_ground','아래의 비어 있는 땅',.39,.78,'날아가는 지팡이 아래에는 인물이 없는 넓은 풍경이 보여요.']],
 wa09:[['wands_fence','뒤에 세운 지팡이들',.26,.65,'붕대 감은 사람 뒤에 여덟 지팡이가 줄지어 서 있어요.']],
 wa10:[['town_ahead','앞에 보이는 마을',.84,.82,'지팡이를 안고 걸어가는 사람 앞쪽에 마을이 보여요.']],
 wapa:[['desert_pyramids','멀리 보이는 피라미드',.85,.80,'지팡이를 바라보는 인물 뒤로 피라미드가 보여요.']],
 wakn:[['upright_wand','똑바로 든 지팡이',.30,.19,'말이 앞발을 드는 동안 기사는 지팡이를 세워 들어요.']],
 waqu:[['black_cat','발치의 검은 고양이',.52,.85,'여왕의 발치에 검은 고양이가 앉아 있어요.']],
 waki:[['salamander_throne','도마뱀 무늬 왕좌',.74,.34,'왕이 앉은 왕좌 뒤쪽에 도마뱀 무늬가 보여요.']],
 peac:[['garden_path','정원으로 난 길',.66,.83,'동전 아래의 정원에는 아치로 이어진 길이 있어요.']],
 pe02:[['ships_in_waves','물결 위의 배들',.80,.76,'인물 뒤 바다에서는 배가 물결을 지나가요.']],
 pe03:[['three_pentacles','아치의 세 동전',.48,.24,'작업장 아치 위에 동전 세 개가 새겨져 있어요.']],
 pe04:[['coins_under_feet','두 발밑의 동전',.51,.82,'앉은 사람의 두 발 아래에도 동전이 하나씩 있어요.']],
 pe05:[['people_in_snow','눈길의 두 사람',.61,.70,'두 사람이 눈 덮인 길을 함께 걸어요.']],
 pe06:[['outstretched_hand','동전을 내미는 손',.39,.60,'저울을 든 사람이 다른 손으로 동전을 내밀어요.']],
 pe07:[['resting_worker','도구에 기댄 사람',.66,.46,'사람은 도구에 몸을 기대고 열매를 바라봐요.']],
 pe08:[['finished_coins','옆에 쌓인 완성 동전',.81,.48,'작업하는 사람 옆에 완성한 동전들이 줄지어 있어요.']],
 pe09:[['garden_vines','주변을 둘러싼 포도덩굴',.47,.57,'새를 올린 인물 주위에는 포도덩굴이 자라 있어요.']],
 pe10:[['ten_pentacles','장면 위의 열 동전',.54,.27,'가족과 개들이 있는 장면 위로 동전 열 개가 놓여 있어요.']],
 pepa:[['ground_beneath','발아래 펼쳐진 들판',.41,.78,'동전을 바라보는 인물의 발아래로 들판이 이어져요.']],
 pekn:[['held_pentacle','앞으로 들어 보인 동전',.65,.23,'멈춰 선 말 위의 기사가 동전을 앞으로 들어요.']],
 pequ:[['flowers_around_throne','왕좌 곁의 꽃들',.75,.73,'동전을 바라보는 여왕의 왕좌 주위에 꽃이 피어 있어요.']],
 peki:[['held_pentacle','손에 든 동전',.69,.45,'황소 머리 장식이 있는 왕좌에서 왕이 동전을 들고 있어요.']],
 cuac:[['dove_over_cup','컵 위의 흰 새',.50,.15,'흰 새가 컵 위쪽으로 내려와 있어요.']],
 cu02:[['winged_lion','두 사람 위의 날개 달린 얼굴',.50,.24,'두 사람 머리 위로 날개 달린 얼굴이 있어요.']],
 cu03:[['circle_of_people','원을 이룬 세 사람',.54,.58,'세 사람이 서로를 향해 서서 원을 이루고 있어요.']],
 cu04:[['folded_arms','팔짱 끼고 앉은 사람',.69,.61,'나무 아래 앉은 사람은 팔짱을 낀 채 컵을 보지 않아요.'],['three_cups','앞에 놓인 세 컵',.34,.82,'앉은 사람의 앞쪽 땅에는 이미 컵 세 개가 놓여 있어요.']],
 cu05:[['spilled_cups','앞에 쓰러진 세 잔',.26,.81,'검은 망토를 입은 사람 앞에는 컵 세 개가 넘어져 있어요.']],
 cu06:[['six_flower_cups','주변의 꽃 담긴 잔들',.45,.78,'꽃을 담은 컵들이 두 사람의 주변에도 놓여 있어요.']],
 cu07:[['silhouette_hand','컵을 향해 뻗은 손',.29,.70,'앞모습이 가려진 사람은 구름 위 컵들 쪽으로 손을 뻗어요.']],
 cu08:[['stacked_cups','뒤에 남겨진 컵들',.36,.82,'떠나는 사람 뒤에는 컵 여덟 개가 쌓여 있어요.']],
 cu09:[['seated_figure','잔 앞에 앉은 사람',.49,.66,'아홉 잔 앞에 한 사람이 두 팔을 모으고 앉아 있어요.']],
 cu10:[['family_below','무지개 아래의 가족',.49,.76,'무지개 아래에서 어른 둘과 아이들이 팔을 들어요.']],
 cupa:[['gazing_page','컵을 바라보는 인물',.62,.41,'젊은 인물이 컵 속 물고기를 바라보고 있어요.']],
 cukn:[['slow_white_horse','천천히 가는 흰 말',.57,.65,'컵을 든 기사의 흰 말은 한 발을 조심스럽게 내딛어요.']],
 cuqu:[['water_beside_throne','왕좌 옆 물가',.23,.75,'뚜껑 있는 컵을 바라보는 여왕 곁에 물이 닿아 있어요.']],
 cuki:[['cup_in_hand','손에 든 컵',.25,.49,'파도에 둘러싸인 왕이 한 손에 컵을 들어요.']],
 swac:[['hand_with_sword','검을 쥔 손',.66,.60,'구름에서 나온 손이 검을 똑바로 쥐고 있어요.']],
 sw02:[['crossed_swords','가슴 앞에 교차한 두 검',.52,.39,'눈을 가린 사람은 검 두 자루를 교차해 들어요.']],
 sw03:[['falling_rain','심장 뒤로 내리는 비',.73,.60,'검에 찔린 심장 뒤쪽으로 비가 내리고 있어요.']],
 sw04:[['three_wall_swords','벽에 걸린 세 검',.68,.38,'누워 있는 인물 뒤 벽에는 검 세 자루가 걸려 있어요.']],
 sw05:[['held_swords','남은 사람이 든 검',.65,.47,'다른 이들이 떠난 뒤 한 사람이 검들을 들고 서 있어요.']],
 sw06:[['covered_passengers','배에 탄 사람들',.27,.52,'배에는 몸을 가린 사람과 작은 인물이 함께 앉아 있어요.']],
 sw07:[['carried_swords','품에 안고 옮기는 다섯 검',.44,.55,'한 사람이 다섯 검을 품에 안고 자리를 떠나요.']],
 sw08:[['surrounding_swords','사람을 둘러싼 검들',.78,.60,'묶인 사람의 주위에 검들이 땅에 꽂혀 있어요.']],
 sw09:[['nine_swords','벽에 늘어선 아홉 검',.44,.23,'잠자리 뒤 어두운 벽에 아홉 검이 가로로 늘어서 있어요.'],['quilt','무늬가 있는 이불',.72,.76,'인물의 무릎 아래에는 여러 무늬의 이불이 덮여 있어요.']],
 sw10:[['swords_in_back','등에 꽂힌 열 검',.48,.43,'엎드린 사람의 등에 열 자루의 검이 꽂혀 있어요.']],
 swpa:[['raised_sword','두 손으로 든 검',.86,.33,'바람 속에 서 있는 인물이 두 손으로 검을 들고 있어요.']],
 swkn:[['rushing_horse','달리는 흰 말',.47,.69,'검을 든 기사가 탄 흰 말은 앞으로 달리고 있어요.']],
 swqu:[['upright_sword','곧게 세운 검',.58,.27,'손을 내민 여왕의 다른 손에는 검이 똑바로 서 있어요.']],
 swki:[['stone_throne','무늬 있는 돌 왕좌',.48,.44,'검을 든 왕이 무늬가 새겨진 돌 왕좌에 앉아 있어요.']],
};
export function symbolsFor(id){
 const first=cardSymbols[id];if(!first)return [];
 return [first,...(additionalSymbols[id]||[]).map(([symbolId,label,x,y,evidence])=>({id:symbolId,label,x,y,evidence}))];
}
