import {getFirestoreClient,isRagDocumentRetrievable,DEFAULT_RAG_COLLECTION,DEFAULT_VECTOR_FIELD,DEFAULT_EMBEDDING_MODEL,DEFAULT_EMBEDDING_DIMENSIONS} from './ragRetriever.js';
import {getActiveRagVersion} from './ragManagerCore.js';
import {embedQuery} from './embeddingProvider.js';
import {classify,approvedUnit} from './tarotRagPolicy.js';
let cache;
const textOf=d=>typeof d.content==='string'?d.content:[d.claim,d.explanation,d.application,d.limitations].filter(x=>typeof x==='string').join('\n');
function vec(d){const v=d[DEFAULT_VECTOR_FIELD];return Array.isArray(v)?v:typeof v?.toArray==='function'?v.toArray():null;}
export async function inventory(){if(cache&&cache.until>Date.now())return cache;const{db}=await getFirestoreClient();const version=await getActiveRagVersion(db);let q=db.collection(DEFAULT_RAG_COLLECTION);if(version)q=q.where('ragVersion','==',version);const[rag,units]=await Promise.all([q.limit(5001).get(),db.collection('ce_knowledge_units').limit(5001).get()]);if(rag.size>5000||units.size>5000)throw Error('TAROT_INVENTORY_LIMIT');const admins=new Set([process.env.SAJUGRAP_ADMIN_UID,...String(process.env.SAJUGRAP_ADMIN_UIDS||'').split(',')].filter(Boolean));const rows=[];let pending=0;for(const doc of rag.docs){const d=doc.data(),kind=classify(d);if(!kind)continue;if(!isRagDocumentRetrievable(d)||d.isNegative===true||d.corpus&&d.corpus!=='production'||(!version&&d.ragVersion)){if(kind==='tarot')pending++;continue}rows.push({id:doc.id,knowledgeId:d.knowledgeId||d.reviewedManifest?.knowledgeId||doc.id,title:String(d.title||d.reviewedManifest?.documentName||doc.id).slice(0,180),text:textOf(d),kind,vector:vec(d),collection:DEFAULT_RAG_COLLECTION,version:version||'legacy'});}
for(const doc of units.docs){const d=doc.data(),kind=classify(d);if(!kind||!admins.has(d.ownerUid))continue;if(!approvedUnit(d)){if(kind==='tarot')pending++;continue}rows.push({id:doc.id,knowledgeId:d.id||doc.id,title:String(d.title||doc.id).slice(0,180),text:textOf(d),kind,vector:vec(d),collection:'ce_knowledge_units',version:String(d.revision||1)});}
const filtered=rows.filter(x=>x.text);cache={rows:filtered,until:Date.now()+120000,summary:{source:'사주그랩 Firebase',tarot:filtered.filter(x=>x.kind==='tarot').length,common:filtered.filter(x=>x.kind==='common').length,pendingTarot:pending,checkedAt:new Date().toISOString()}};return cache;}
const tokens=s=>[...new Set(String(s).toLowerCase().match(/[가-힣a-z0-9]{2,}/g)||[])];
export function scoreRow(row,query,queryVector){const content=(row.title+' '+row.text).toLowerCase(),terms=tokens(query);const lexical=terms.filter(t=>content.includes(t)).length/Math.max(terms.length,1);let semantic=0;if(queryVector&&row.vector?.length===queryVector.length&&row.vector.every(Number.isFinite)){let dot=0,a=0,b=0;for(let i=0;i<queryVector.length;i++){dot+=queryVector[i]*row.vector[i];a+=queryVector[i]**2;b+=row.vector[i]**2;}semantic=dot/(Math.sqrt(a*b)||1)}return{score:semantic*.7+lexical*.3,lexical,semantic}}
export async function retrieve(input){const inv=await inventory();if(!inv.rows.length)return{...inv.summary,results:[],mode:'no-approved-knowledge'};const recent=input.messages.filter(x=>x.role==='user').slice(-3).map(x=>x.text).join(' ');const query=['타로 상담 구체적 질문 명료화 의사결정 상담 대화 기술',input.question,recent,...input.cards.map(c=>`${c.name} ${c.en} ${c.reversed?'역방향':'정방향'} ${c.position}`)].join('\n').slice(0,5000);let queryVector=null;let mode='keyword';if(inv.rows.some(x=>x.vector?.length===DEFAULT_EMBEDDING_DIMENSIONS)){const e=await embedQuery(query,{model:DEFAULT_EMBEDDING_MODEL,dimensions:DEFAULT_EMBEDDING_DIMENSIONS});queryVector=e.vector;mode='hybrid';}
const ranked=inv.rows.map(row=>({...row,...scoreRow(row,query,queryVector)})).filter(x=>x.lexical>0||x.semantic>=.4).sort((a,b)=>b.score-a.score);const out=[],seen=new Set();function add(r){if(!r||seen.has(r.knowledgeId))return;seen.add(r.knowledgeId);out.push(r)}
// Reserve one best matching source per selected card before broad context.
for(const c of input.cards){if(out.filter(x=>x.kind==='tarot').length>=6)break;const aliases=[c.name,c.en].map(x=>x.toLowerCase());add(ranked.find(r=>r.kind==='tarot'&&aliases.some(a=>(r.title+' '+r.text).toLowerCase().includes(a))))}
for(const r of ranked.filter(r=>r.kind==='tarot')){if(out.filter(x=>x.kind==='tarot').length>=6)break;add(r)}
const userQuery=[input.question,recent].join(' ');
const commonRelevant=r=>{const scope=r.title+' '+r.text.slice(0,500);for(const family of [/부모|자녀|아동|양육/,/의료|환자|간호|보건/,/노동|근로|직장|조직/]){if(family.test(scope)&&!family.test(userQuery))return false;}const match=scoreRow(r,userQuery,queryVector);return match.lexical>=.08&&(match.semantic>=.55||!queryVector);};
const dialogue=ranked.find(r=>r.kind==='common'&&/상담|대화|질문|명료화|의사결정/.test(r.title+' '+r.text.slice(0,300))&& !/부모|자녀|아동|의료|환자/.test(r.title));add(dialogue);
for(const r of ranked.filter(r=>r.kind==='common'&&commonRelevant(r))){if(out.filter(x=>x.kind==='common').length>=2)break;add(r)}
return{...inv.summary,mode,results:out.slice(0,8).map(({vector,...r})=>({...r,text:r.text.slice(0,3000),score:Math.round(r.score*1000)/1000}))};}
