import crypto from 'node:crypto';
import {requireRagAdmin} from '../lib/ragAdminAuth.js';
import {waitUntil} from '@vercel/functions';
import {limit} from '../lib/tarotRateLimit.js';
import {recentAudits} from '../lib/tarotRuntimeStore.js';
import {saveAudit,refreshSnapshot} from '../lib/tarotSnapshot.js';
import {inventory,retrieve,sourceInventory} from '../lib/tarotRag.js';
import {validateTarot} from '../lib/tarotValidation.js';
const ALLOWED=new Set(['https://tarot-with-you.vercel.app','https://saju-grap.vercel.app']);
import {READING_VERSION,readingMaterial,READING_TASK} from '../lib/tarotReadingMaterial.js';
import {SYSTEM,parseResponse} from '../lib/tarotResponse.js';
async function bounded(label,work,ms){let timer;const start=Date.now();try{return await Promise.race([work(),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error(label+'_TIMEOUT')),ms)})])}finally{clearTimeout(timer);console.info('tarot_stage',{stage:label,ms:Date.now()-start})}}
async function generate(input,rag){const payload=JSON.stringify({action:input.action,visualMode:input.visualMode,question:input.question,conversation:input.messages,context:input.context,rounds:input.rounds.map(r=>({...r,cards:r.cards.map(c=>readingMaterial(c,input))})),RAG_CONTEXT:rag.results.map((r,i)=>({ref:`지식 ${i+1}`,kind:r.kind,title:r.title,content:r.text})),ragStatus:rag.results.length?'retrieved':'no matching approved knowledge',CURRENT_TASK:{action:input.action,roundCount:input.rounds.length,instruction:input.action==='reading'?READING_TASK:input.action==='clarify'?'160자 이내 본론과 짧은 선택지. 기본3장만 사용하며 배열 추천 대화는 생략한다.':'현재 카드와 사용자의 추가 질문을 연결해 첫 문장부터 답하라. 300자 이내로 핵심 근거와 새로 밝혀진 점을 말하고, 끝에 질문이나 추가 뽑기를 의무적으로 제안하지 않는다.'}});let last;
for(const provider of ['openai','gemini']){try{let url,headers,body;if(provider==='openai'){if(!process.env.OPENAI_API_KEY)continue;url='https://api.openai.com/v1/responses';headers={Authorization:`Bearer ${process.env.OPENAI_API_KEY}`};body={model:process.env.TAROT_MODEL||process.env.OPENAI_MODEL||'gpt-5.6-luna',instructions:SYSTEM,input:payload,max_output_tokens:9000,store:false};}else{if(!process.env.GEMINI_API_KEY)continue;url=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(process.env.GEMINI_MODEL||'gemini-3.7-flash')}:generateContent`;headers={'x-goog-api-key':process.env.GEMINI_API_KEY};body={systemInstruction:{parts:[{text:SYSTEM}]},contents:[{role:'user',parts:[{text:payload}]}],generationConfig:{maxOutputTokens:9000}};}
const r=await fetch(url,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(provider==='openai'?55000:25000)});if(!r.ok)throw Error(provider+'_'+r.status);const d=await r.json();const text=provider==='openai'?(d.output??[]).flatMap(x=>x.content??[]).filter(x=>x.type==='output_text').map(x=>x.text).join('\n'):(d.candidates?.[0]?.content?.parts??[]).filter(x=>!x.thought).map(x=>x.text||'').join('');if(!text||d.status==='incomplete')throw Error('EMPTY_RESPONSE');return{...parseResponse(text,input),provider};}catch(e){last=e;console.warn('tarot_generation_retry',{provider,code:String(e.message).slice(0,80)})}}
throw last||Error('MODEL_NOT_CONFIGURED');}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');const origin=req.headers.origin;if(origin&&!ALLOWED.has(origin))return res.status(403).json({error:'허용되지 않은 요청입니다.'});if(origin)res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');if(req.method==='OPTIONS'){res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,Authorization');return res.status(204).end()}
if(req.method==='GET'){if(req.query?.admin==='1'){try{await requireRagAdmin(req)}catch(e){return res.status(e.httpStatus||401).json({error:'관리자 계정으로 로그인해 주세요.'})}try{const inv=await inventory();const audits=await recentAudits();return res.status(200).json({rag:inv.summary,guide:{version:'2026-09-29-v4',count:78,basis:'앱에 표시하는 RWS 그림 직접 대조 · 카드별 한국어 성찰 원고. 정·역방향은 앱에서 채택한 해석이며 단일한 정답이 아닙니다.',images:'https://github.com/seven102161/elaine-tarot-cards',repairs:'https://github.com/metabismuth/tarot-json'},readings:audits})}catch{return res.status(503).json({error:'관리자 정보를 불러오지 못했어요.'})}}return res.status(200).json({available:!!(process.env.OPENAI_API_KEY||process.env.GEMINI_API_KEY)})}
if(req.method==='POST'&&req.query?.admin==='1'){try{await requireRagAdmin(req)}catch(e){return res.status(e.httpStatus||401).json({error:'관리자 계정으로 로그인해 주세요.'})}try{return res.status(200).json({rag:await refreshSnapshot(sourceInventory,{force:true})})}catch{return res.status(503).json({error:'원본 지식 동기화에 실패했어요. 저장된 풀이용 사본은 유지됩니다.'})}}
if(req.method!=='POST')return res.status(405).json({error:'지원하지 않는 요청입니다.'});let input;try{let b=typeof req.body==='string'?JSON.parse(req.body):req.body;if(JSON.stringify(b).length>100000)throw Error();input=validateTarot(b)}catch{return res.status(400).json({error:'질문과 카드 정보를 확인해 주세요.'})}
try{console.info('tarot_request',{action:input.action,version:READING_VERSION});await bounded('rate_limit',()=>limit(req),8000);let rag;try{rag=await bounded('retrieval',()=>retrieve(input),12000)}catch(e){console.warn('tarot_retrieval_unavailable',{code:String(e.message).slice(0,80)});rag={results:[],mode:'guide-only-temporary'}}const result=await bounded('generation',()=>generate(input,rag),81000);const auditId=crypto.randomUUID();waitUntil(saveAudit(auditId,{createdAt:Date.now(),action:input.action,guideVersion:'2026-09-29-v4',readingVersion:READING_VERSION,spreads:input.rounds.map(r=>r.spread),cards:input.cards.map(c=>({name:c.name,reversed:c.reversed,position:c.position})),sources:rag.results.map(r=>({title:r.title,kind:r.kind,collection:r.collection,score:r.score})),mode:rag.mode}).catch(()=>console.warn('tarot_audit_unavailable')));console.info('tarot_reading_ready',{action:input.action,sources:rag.results.length,mode:rag.mode});const {provider,...publicResult}=result;return res.status(200).json({...publicResult,auditId})}catch(e){console.error('tarot_failed',{code:String(e.message).slice(0,80)});const quota=/quota exceeded/i.test(String(e.message));return res.status(e.message==='RATE_LIMIT'?429:503).json({error:quota?'현재 상담 서버의 사용 한도에 도달해 새 풀이를 잠시 만들 수 없어요. 질문과 뽑은 카드는 그대로 보관됩니다.':e.message==='RATE_LIMIT'?'상담 이용량이 많아요. 잠시 후 다시 이용해 주세요.':'상담 연결이 잠시 어려워요. 뽑은 카드는 그대로 유지되니 다시 시도해 주세요.'})}}
