import crypto from 'node:crypto';
import {requireRagAdmin} from '../lib/ragAdminAuth.js';
import {waitUntil} from '@vercel/functions';
import {limit} from '../lib/tarotRateLimit.js';
import {recentAudits} from '../lib/tarotRuntimeStore.js';
import {saveAudit,refreshSnapshot} from '../lib/tarotSnapshot.js';
import {inventory,retrieve,sourceInventory} from '../lib/tarotRag.js';
import {validateTarot} from '../lib/tarotValidation.js';
const ALLOWED=new Set(['https://tarot-with-you.vercel.app','https://saju-grap.vercel.app']);
import {ENGINE_VERSION as READING_VERSION} from '../lib/tarotEngine.js';
import {generateTarot as generate} from '../lib/tarotGenerator.js';
async function bounded(label,work,ms){let timer;const start=Date.now();try{return await Promise.race([work(),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error(label+'_TIMEOUT')),ms)})])}finally{clearTimeout(timer);console.info('tarot_stage',{stage:label,ms:Date.now()-start})}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');const origin=req.headers.origin;if(origin&&!ALLOWED.has(origin))return res.status(403).json({error:'허용되지 않은 요청입니다.'});if(origin)res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');if(req.method==='OPTIONS'){res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,Authorization');return res.status(204).end()}
if(req.method==='GET'){if(req.query?.admin==='1'){try{await requireRagAdmin(req)}catch(e){return res.status(e.httpStatus||401).json({error:'관리자 계정으로 로그인해 주세요.'})}try{const inv=await inventory();const audits=await recentAudits();return res.status(200).json({rag:inv.summary,guide:{version:'2026-10-07-plain-meaning-v13',count:78,basis:'앱에 표시하는 RWS 그림 직접 대조 · 카드별 한국어 성찰 원고. 정·역방향은 앱에서 채택한 해석이며 단일한 정답이 아닙니다.',images:'https://github.com/seven102161/elaine-tarot-cards',repairs:'https://github.com/metabismuth/tarot-json'},readings:audits})}catch{return res.status(503).json({error:'관리자 정보를 불러오지 못했어요.'})}}return res.status(200).json({available:!!(process.env.OPENAI_API_KEY||process.env.GEMINI_API_KEY)})}
if(req.method==='POST'&&req.query?.admin==='1'){try{await requireRagAdmin(req)}catch(e){return res.status(e.httpStatus||401).json({error:'관리자 계정으로 로그인해 주세요.'})}try{return res.status(200).json({rag:await refreshSnapshot(sourceInventory,{force:true})})}catch{return res.status(503).json({error:'원본 지식 동기화에 실패했어요. 저장된 풀이용 사본은 유지됩니다.'})}}
if(req.method!=='POST')return res.status(405).json({error:'지원하지 않는 요청입니다.'});let input;try{let b=typeof req.body==='string'?JSON.parse(req.body):req.body;if(JSON.stringify(b).length>100000)throw Error();input=validateTarot(b)}catch{return res.status(400).json({error:'질문과 카드 정보를 확인해 주세요.'})}
try{console.info('tarot_request',{action:input.action,version:READING_VERSION});await bounded('rate_limit',()=>limit(req),8000);let rag;try{rag=await bounded('retrieval',()=>retrieve(input),12000)}catch(e){console.warn('tarot_retrieval_unavailable',{code:String(e.message).slice(0,80)});rag={results:[],mode:'guide-only-temporary'}}const result=await bounded('generation',()=>generate(input,rag),81000);const auditId=crypto.randomUUID();waitUntil(saveAudit(auditId,{createdAt:Date.now(),action:input.action,guideVersion:'2026-10-07-plain-meaning-v13',readingVersion:READING_VERSION,generation:result.telemetry,spreads:input.rounds.map(r=>r.spread),cards:input.cards.map(c=>({name:c.name,reversed:c.reversed,position:c.position})),sources:rag.results.map(r=>({title:r.title,kind:r.kind,collection:r.collection,score:r.score})),mode:rag.mode}).catch(()=>console.warn('tarot_audit_unavailable')));console.info('tarot_reading_ready',{action:input.action,sources:rag.results.length,mode:rag.mode});const {provider,telemetry,interpretation,...publicResult}=result;return res.status(200).json({...publicResult,auditId})}catch(e){console.error('tarot_failed',{code:String(e.message).slice(0,80)});const quota=/quota exceeded/i.test(String(e.message));return res.status(e.message==='RATE_LIMIT'?429:503).json({error:quota?'현재 상담 서버의 사용 한도에 도달해 새 풀이를 잠시 만들 수 없어요. 질문과 뽑은 카드는 그대로 보관됩니다.':e.message==='RATE_LIMIT'?'상담 이용량이 많아요. 잠시 후 다시 이용해 주세요.':'상담 연결이 잠시 어려워요. 뽑은 카드는 그대로 유지되니 다시 시도해 주세요.'})}}
